#
# Simple development makefile
#

#
# add more flags here,
# but don't remove the "+="
#
CFLAGS += -O2 -std=c99 -g -lm -Wall #-Wsign-compare -Wfloat-equal -Wformat-security #-Werror
CPPFLAGS += 
LDFLAGS += 


all: game

clean:
	-rm -f game

install:


.PHONY: all install clean

# end of development makefile
